/** Auto-generated by scripts/generate-content-manifest.mjs — do not edit by hand. */
export const contentManifest = {
  recipes: [
  "brioche-bread",
  "chapati",
  "coconut-rice",
  "cozy-chicken-soup",
  "english-peas-stew",
  "grandmas-banana-bread",
  "honey-roasted-vegetables",
  "lemon-garlic-pasta",
  "matooke-with-groundnut-sauce",
  "mushroom-sauce",
  "pork-curry",
  "roasted-beef-luwombo",
  "sandwich-bread"
],
  stories: [
  "chapati-and-rolex",
  "first-kitchen-memory",
  "growing-up-in-uganda",
  "my-parents-love",
  "my-sister-salma",
  "through-the-ceiling",
  "why-i-cook"
],
} as const;
